const assert=require('node:assert/strict');
const {syncDashboardLane,gen5MatchRows}=require('./paisho_dashboard_lanes.js');
global.Option=class {constructor(label,value){this.textContent=label;this.value=value;}};
const select={dataset:{},options:[],value:'Historical',disabled:true,replaceChildren(...options){this.options=options;}};
const ensemble=[['Historical','Toutes'],...['3.1','3.2','3.3','3.4','3.5'].map(g=>['Gen'+g,'Contre '+g]),['Selfplay','Auto-jeu'],['Checkpoint','Versions']];
const old=[['Historical','Gen3.1'],['Selfplay','Auto-jeu'],['Checkpoint','Versions']];
const third=[['Selfplay','Gen3.5'],['Gen3.1','Contre 3.1'],['Gen3.3','Contre 3.3']];
assert.equal(syncDashboardLane(select,'V5 ensemble',ensemble,'Gen3.1'),'Gen3.1');
assert.equal(select.disabled,false);
select.value='Gen3.5';
assert.equal(syncDashboardLane(select,'V5 ensemble',ensemble,'Gen3.1'),'Gen3.5');
assert.equal(syncDashboardLane(select,'Gen3.5',third,'Gen3.3'),'Gen3.3');
assert(!select.options.some(o=>o.value==='Gen3.5'));
select.value='Gen3.1';
assert.equal(syncDashboardLane(select,'V5 ensemble',ensemble,'Gen3.1'),'Gen3.5');
assert.equal(syncDashboardLane(select,'V5 standard',old,'Historical'),'Historical');
select.value='Checkpoint';
assert.equal(syncDashboardLane(select,'V5 legacy',old,'Historical'),'Historical');
assert.equal(select.disabled,false);
assert.equal(syncDashboardLane(select,'Gen3.5',third,'Gen3.3'),'Gen3.1');
assert.equal(syncDashboardLane(select,'V5 standard',old,'Historical'),'Checkpoint');
assert.equal(syncDashboardLane(select,'V5 ensemble',ensemble.map(([v,l])=>[v,'EN '+l]),'Gen3.1'),'Gen3.5');
assert(select.options.every(o=>o.textContent.startsWith('EN ')));
const history={match_bins:[{lane:'Historical',generation:'Gen3.1',budget:8},{lane:'Historical',generation:'Gen3.5',budget:8},{lane:'Selfplay',budget:null}]};
assert.equal(gen5MatchRows(history,'Gen3.5').length,1);
assert.equal(gen5MatchRows(history,'Gen3.5')[0].generation,'Gen3.5');
assert.equal(gen5MatchRows(history,'Historical').length,2);
assert.equal(gen5MatchRows(history,'Selfplay').length,1);
assert.equal(gen5MatchRows(history,'Checkpoint').length,0);
assert.equal(gen5MatchRows({bins:[{budget:8,games:4}]},'Gen3.1')[0].games,4);
console.log('Selector modes, persistent choices, language changes and opponent filters passed.');
